# 🔢 Notebook 4 — NumPy: Arreglos y Operaciones Vectorizadas
### Unidad 2 | Python para Ciencia de Datos | UADE

> 📚 Basado en **Python for Data Analysis, 3rd Ed.** — Wes McKinney, Cap. 4  
> Libro disponible en: https://wesmckinney.com/book/numpy-basics

---

## ¿Por qué NumPy?

NumPy es la librería fundamental para computación numérica en Python. Su estructura central es el **ndarray** (N-dimensional array), que permite realizar operaciones matemáticas sobre arreglos completos **sin escribir bucles `for`**.

Esta capacidad se llama **vectorización** y es hasta 100 veces más rápida que Python puro.


In [1]:
import numpy as np
print(f'NumPy version: {np.__version__}')

NumPy version: 2.3.2


---
## 1. Creando arrays

In [2]:
# Desde una lista de Python
arr1d = np.array([6, 7.5, 8, 0, 1])
print("1D:", arr1d)
print("dtype:", arr1d.dtype)
print("shape:", arr1d.shape)

1D: [6.  7.5 8.  0.  1. ]
dtype: float64
shape: (5,)


In [3]:
# Array 2D desde lista de listas
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])
print("2D:\n", arr2d)
print("shape:", arr2d.shape)   # (filas, columnas)
print("ndim:", arr2d.ndim)

2D:
 [[1 2 3 4]
 [5 6 7 8]]
shape: (2, 4)
ndim: 2


In [4]:
# Funciones de creación útiles
print("zeros:  ", np.zeros(5))
print("ones:   ", np.ones((2, 3)))
print("arange: ", np.arange(10))
print("linspace:", np.linspace(0, 1, 5))   # 5 valores entre 0 y 1

# Identidad (útil en álgebra lineal)
print("eye:\n", np.eye(3))

zeros:   [0. 0. 0. 0. 0.]
ones:    [[1. 1. 1.]
 [1. 1. 1.]]
arange:  [0 1 2 3 4 5 6 7 8 9]
linspace: [0.   0.25 0.5  0.75 1.  ]
eye:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


---
## 2. Tipos de datos (dtype)

In [5]:
arr_int   = np.array([1, 2, 3], dtype=np.int32)
arr_float = np.array([1, 2, 3], dtype=np.float64)

print("int32:  ", arr_int.dtype)
print("float64:", arr_float.dtype)

# Convertir tipos con astype
arr_cast = arr_int.astype(np.float64)
print("convertido:", arr_cast.dtype)

int32:   int32
float64: float64
convertido: float64


---
## 3. Aritmética vectorizada

Con NumPy, las operaciones matemáticas se aplican **elemento a elemento** automáticamente:

In [6]:
arr = np.array([[1., 2., 3.],
                [4., 5., 6.]])

print("arr * arr:\n", arr * arr)    # producto elemento a elemento
print("arr ** 2:\n", arr ** 2)     # potencia elemento a elemento
print("1 / arr:\n", 1 / arr)       # división elemento a elemento

# Comparaciones → devuelven booleanos
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print("arr2 > arr:\n", arr2 > arr)

arr * arr:
 [[ 1.  4.  9.]
 [16. 25. 36.]]
arr ** 2:
 [[ 1.  4.  9.]
 [16. 25. 36.]]
1 / arr:
 [[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
arr2 > arr:
 [[False  True False]
 [ True False  True]]


---
## 4. Indexing y Slicing

In [7]:
arr = np.arange(10)
print("arr:", arr)
print("arr[5]:", arr[5])
print("arr[2:6]:", arr[2:6])

# IMPORTANTE: los slices en NumPy son VISTAS, no copias
arr_slice = arr[5:8]
arr_slice[:] = 99
print("arr después de modificar el slice:", arr)

# Para hacer una copia real:
arr_copy = arr[5:8].copy()

arr: [0 1 2 3 4 5 6 7 8 9]
arr[5]: 5
arr[2:6]: [2 3 4 5]
arr después de modificar el slice: [ 0  1  2  3  4 99 99 99  8  9]


In [ ]:
# Indexing en 2D
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print("fila 0:", arr2d[0])
print("elemento [1,2]:", arr2d[1, 2])
print("primeras 2 filas:\n", arr2d[:2])
print("primeras 2 filas, columna 1 en adelante:\n", arr2d[:2, 1:])

---
## 5. Indexing booleano

In [ ]:
nombres = np.array(["Ana", "Luis", "Ana", "Carlos", "Luis"])
scores  = np.array([85, 92, 78, 95, 88])

# Filtrar scores de Ana
print("Scores de Ana:", scores[nombres == "Ana"])

# Combinar condiciones con & (AND) y | (OR)
print("Ana o Carlos:", scores[(nombres == "Ana") | (nombres == "Carlos")])

# Modificar valores que cumplen una condición
scores[scores < 80] = 80
print("Scores con mínimo 80:", scores)

---
## 6. Funciones universales (ufuncs)

Funciones que operan **elemento a elemento** sobre arrays completos:

In [ ]:
arr = np.arange(10)
print("sqrt:", np.sqrt(arr))
print("exp: ", np.exp(arr[:5]))

# Ufuncs binarias (operan sobre 2 arrays)
x = np.array([1.5, 3.2, 0.8])
y = np.array([2.1, 0.5, 4.4])
print("maximum:", np.maximum(x, y))
print("add:    ", np.add(x, y))

---
## 7. Estadística sobre arrays

In [ ]:
rng = np.random.default_rng(seed=42)
datos = rng.standard_normal((4, 5))   # matriz 4x5 de normales
print("datos:\n", datos.round(2))
print()
print("mean total:", datos.mean())
print("sum  total:", datos.sum())
print("std  total:", datos.std())
print()
# axis=0 → por columna (↓)  |  axis=1 → por fila (→)
print("mean por fila:  ", datos.mean(axis=1).round(2))
print("sum  por columna:", datos.sum(axis=0).round(2))

---
## 8. numpy.where — lógica condicional vectorizada

In [ ]:
arr = rng.standard_normal((4, 4))
print("arr:\n", arr.round(2))

# Reemplazar positivos con 2, negativos con -2
resultado = np.where(arr > 0, 2, -2)
print("\nwhere (>0 → 2, else -2):\n", resultado)

# Reemplazar solo los positivos con 1
print("\nwhere (>0 → 1, else mantener):\n", np.where(arr > 0, 1, arr).round(2))

---
## 9. Álgebra lineal

In [ ]:
A = np.array([[1., 2.], [3., 4.]])
B = np.array([[5., 6.], [7., 8.]])

print("Producto matricial A @ B:\n", A @ B)
print("Transpuesta A.T:\n", A.T)

# Inversa
from numpy.linalg import inv
print("Inversa de A:\n", inv(A).round(4))

---
## 10. Ejemplo final: simulación de caminata aleatoria

Ejemplo del libro (sección 4.7): simulamos 1000 pasos de una caminata aleatoria usando vectorización.

In [ ]:
import matplotlib.pyplot as plt

rng = np.random.default_rng(seed=12345)
nsteps = 1000

# Vectorización: generamos todos los pasos de una vez
draws = rng.integers(0, 2, size=nsteps)   # 0 o 1
steps = np.where(draws == 0, 1, -1)       # +1 o -1
walk  = steps.cumsum()                     # posición acumulada

print(f"Mínimo: {walk.min()} | Máximo: {walk.max()}")
print(f"Primer cruce de ±10: paso {(np.abs(walk) >= 10).argmax()}")

plt.figure(figsize=(10, 3))
plt.plot(walk[:200])
plt.axhline(0, color='red', linestyle='--', alpha=0.5)
plt.title("Caminata aleatoria — primeros 200 pasos")
plt.xlabel("Pasos"); plt.ylabel("Posición")
plt.tight_layout()
plt.show()